spring.datasource.url=jdbc:postgresql://${DB_host}/Qual_ea_Boa
spring.datasource.username=${DB_User}
spring.datasource.password=${Password}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect